// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetProjectsResponse, CreateProjectData, CreateProjectResponse } from './types.gen';

export class DefaultService {
    /**
     * @returns ApiResponseList_Project_ Ok
     * @throws ApiError
     */
    public static getProjects(): CancelablePromise<GetProjectsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/v1/projects'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ApiResponse_Project_ Created
     * @throws ApiError
     */
    public static createProject(data: CreateProjectData): CancelablePromise<CreateProjectResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/v1/projects',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}