// This file is auto-generated by @hey-api/openapi-ts

/**
 * Stringified UUIDv4.
 * See [RFC 4112](https://tools.ietf.org/html/rfc4122)
 */
export type UUID = string;

export type Project = {
    shared_with_client: boolean;
    updated_by: UUID;
    last_updated: string;
    date_created: string;
    name: string;
    id: UUID;
};

export type ApiInternalError = {
    message: string;
};

export type ApiResponseListMeta = {
    total: number;
};

export type ApiResponseList_Project_ = {
    data: Array<Project>;
    errors: Array<ApiInternalError>;
    meta?: ApiResponseListMeta;
};

export type ApiResponse_Project_ = {
    data: Project;
    errors: Array<ApiInternalError>;
    meta?: number | null;
};

export type ProjectCreateParams = {
    name: string;
};

export type GetProjectsResponse = ApiResponseList_Project_;

export type CreateProjectData = {
    requestBody: ProjectCreateParams;
};

export type CreateProjectResponse = ApiResponse_Project_;

export type $OpenApiTs = {
    '/v1/projects': {
        get: {
            res: {
                /**
                 * Ok
                 */
                200: ApiResponseList_Project_;
            };
        };
        post: {
            req: CreateProjectData;
            res: {
                /**
                 * Created
                 */
                201: ApiResponse_Project_;
            };
        };
    };
};